# see https://s.apache.org/asfyaml
github:
  description: "Apache Maven Release (Plugin)"
  homepage: https://maven.apache.org/maven-release/
  labels:
    - java
    - build-management
    - maven-plugins
    - maven
